src/layouts/RecursiveMenu/TreeMenu.vue, src/modules/Product/composables/Category/useCreateOrEdit.ts, src/modules/Product/composables/Category/useIndex.ts, src/modules/Product/routes/index.ts, src/modules/Product/services/index.ts, src/modules/Product/views/Category/Create.vue, src/modules/Product/views/Category/Edit.vue, src/modules/Product/views/Category/Index.vue, src/modules/Product/views/Category1/CreateOrEdit.vue, src/modules/Product/views/Category1/Index.vue
feat: Working tablegrid of categories
=> feat: Working tablegrid of categories

src/layouts/PageFoot.vue, src/modules/Product/services/CategoryService.ts, src/modules/Product/services/index.ts, src/modules/Product/views/Category/Create.vue, src/modules/Product/views/Category/Edit.vue, src/modules/Product/views/Category/Index.vue
=> feat: CRUD of Category

src/modules/Product/composables/Mark/useCreateOrEdit.ts, src/modules/Product/composables/Mark/useIndex.ts, src/modules/Product/routes/index.ts, src/modules/Product/services/MarkService.ts, src/modules/Product/views/Mark/CreateOrEdit.vue, src/modules/Product/views/Mark/Index.vue, src/modules/Product/views/Product/CreateOrEdit.vue, src/modules/Product/views/Product/Index.vue
=> feat: List Marks to CRUD

src/modules/Product/composables/Mark/useCreateOrEdit.ts, src/modules/Product/composables/Mark/useIndex.ts, src/modules/Product/services/MarkService.ts
=> feat: CRUD of Mark

src/components/AppPending.vue, src/composables/useHttp.ts, src/modules/Product/composables/Product/useIndex.ts, src/modules/Product/routes/index.ts, src/modules/Product/views/Product/Index.vue, src/modules/Product/views/Product/TabPresentation.vue, src/modules/Product/views/Product/TabProduct.vue, src/modules/Product/views/Product/Tabs.vue, src/plugins/components.ts
feat: Dynamic tabs for products and presentations
=> feat: Dynamic tabs for products and presentations

src/modules/Product/views/Product/Index.vue
feat: Add category and mark to product list
=> feat: Add category and mark to product list

src/modules/Product/views/Product/TabImage.vue, src/modules/Product/views/Product/TabProduct.vue, src/modules/Product/views/Product/Tabs.vue
=> feat: Product tab form design

src/modules/Product/views/Product/TabPresentation.vue
=> Presentation tab form design

src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/services/CategoryService.ts, src/modules/Product/services/ProductService.ts, src/modules/Product/views/Product/TabProduct.vue, src/modules/Product/views/Product/Tabs.vue
feat: Show list of categories to fill select
=> feat: Show list of categories to fill select

src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/services/MarkService.ts, src/modules/Product/views/Product/TabProduct.vue
feat: Show list of marks to fill select
=> feat: Show list of marks to fill select

src/assets/css/forms.css, src/modules/Product/views/Product/TabPresentation.vue
=> feat: Add Teleport

src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabProduct.vue, src/plugins/components.ts
=> wip: Start with packing

src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/views/Product/Tabs.vue
wip: Show measureUnit.name selected
=> wip: Show measureUnit.name selected

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/views/Product/Tabs.vue
feat: Provide/Inject to measureUnit
=> feat: Provide/Inject to measureUnit

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/views/Product/Tabs.vue
refactor: Provide/Inject to measureUnit
=> refactor: Provide/Inject to measureUnit

src/assets/css/forms.css, src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TabProduct.vue
=> feat: Packing Modal

src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/usePacking.ts, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/services/MarkService.ts, src/modules/Product/views/Product/Tabs.vue
refactor: Packing Modal to compodable
=> refactor: Packing Modal to compodable

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useTabProduct.ts
fix: TypeScript of Provide/Inject
=> fix: TypeScript of Provide/Inject

src/modules/Product/composables/Product/usePacking.ts
feat: Add the measure unit in the packaging
=> feat: Add the measure unit in the packaging

src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabPresentation.vue
feat: Pass packaging payload from modal to presentation
=> feat: Pass packaging payload from modal to presentation

src/components/AppSelect.vue, src/modules/Product/components/Product/TabProduct.vue, src/types/Option.ts
fix: Typing of html select element
=> fix: Typing of html select element

src/components/AppRadio.vue, src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/composables/Product/usePacking.ts, src/plugins/components.ts
feat: Prepare panel to add presentation
=> feat: Prepare panel to add presentation

src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/services/ProductService.ts
feat: Prepare ServiceProduct for insert and update
=> feat: Prepare ServiceProduct for insert and update

src/modules/Product/components/Product/FormProduct.vue, src/modules/Product/components/Product/TabProduct.vue, src/modules/Product/composables/Product/useFormProduct.ts, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/composables/Product/zuseTabProductBack.ts
feat: Separate FormProduct (child) from TabProduct (parent)
=> Feat form product

src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/types/Presentation.ts, src/types/RadioOption.ts
=> feat: Form presentation

src/assets/css/forms.css, src/modules/Product/components/Product/ModalPacking.vue
=> style: ModalPacking

package.json, src/modules/Product/composables/Product/useTabProduct.ts, src/modules/Product/services/ProductService.ts
feat: Pass data to api to update product
=> feat: Pass data to api to update product

src/modules/Product/composables/Product/useTabProduct.ts
feat: Insert and update product
=> feat: Insert and update product

src/composables/useIsErrorShowIt.ts, src/modules/Product/components/Product/FormProduct.vue
feat: If there is an error in the form show it
=> feat: If there is an error in the form show it

package-lock.json, package.json
=> feat: Vuelidate install

src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/components/Product/FormProduct.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/composables/Product/useFormPresentation.ts, src/modules/Product/composables/Product/useFormProduct.ts, src/modules/Product/composables/Product/useTabPresentation.ts
refactor: Separate UI from business rule
=> refactor: Separate UI from business rule

src/composables/useSidebar.ts, src/layouts/Header.vue, src/layouts/RecursiveMenu/TreeMenu.vue, src/layouts/Sidebar.vue
feat: Ability to hide sidebar menu when screen is wide
=> feat: Ability to hide sidebar menu when screen is wide

src/layouts/Header.vue, src/layouts/SelectTheme.vue
feat: Changing the theme; fix: Transparent in the header
=> feat: Changing the theme; fix: Transparent in the header

src/components/AppTextarea.vue, src/modules/Product/components/Product/FormPacking.vue, src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/components/Product/ModalPacking.vue, src/modules/Product/composables/Product/useFormPacking.ts, src/modules/Product/composables/Product/usePacking.ts
=> feat: Validating ModalPacking

src/components/AppRadioGroup.vue, src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/components/Product/FormProduct.vue, src/modules/Product/composables/Product/useFormPresentation.ts
feat: Validate Presentations form fields before being saved.
=> feat: Validate Presentations form fields before being saved

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/composables/Product/useTabPresentation.ts, src/modules/Product/services/PresentationService.ts
feat: Send Presentations form fields to the backend after being validated
=> feat: Send Presentations form fields to the backend after being validated

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/composables/Product/useTabPresentation.ts, src/modules/Product/services/PresentationService.ts
feat: List product presentations.
=> feat: List product presentations

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/composables/Product/useTabPresentation.ts, src/modules/Product/types/Presentation.ts
feat: List of presentations after inserting it.
=> feat: List of presentations after inserting it

src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/composables/Product/useFormPresentation.ts, src/modules/Product/composables/Product/useTabPresentation.ts
feat: Edit presentation when edit button is clicked.
=> feat: Edit presentation when edit button is clicked

src/modules/Product/composables/Product/useFormPresentation.ts, src/modules/Product/composables/Product/useTabPresentation.ts, src/modules/Product/services/PresentationService.ts
feat: Send Presentations form fields to the backend to Update.
=> feat: Send Presentations form fields to the backend to Update

src/modules/Product/components/Product/TabPresentation.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/composables/Product/useIndex.ts, src/modules/Product/composables/Product/useTabPresentation.ts
feat: Send ID presentation to the backend to remove it.
=> feat: Send ID presentation to the backend to remove it

.env.example.docker, README.md, docker-compose.dev.yml, docker-compose.yml, vite.config.ts
feat: Containerize the app using docker.
=> feat: Containerize the app using docker

src/modules/Product/components/Product/ModalImage.vue, src/modules/Product/components/Product/TablePresentation.vue, vite.config.ts
feat: Create a form that captures the image of each presentation
=> feat: Create a form that captures the image of each presentation

src/assets/css/app.css, src/modules/Product/components/Product/ModalImage.vue, src/modules/Product/views/Product/Tabs.vue
feat: Create preview image for upload.
=> feat: Create preview image for upload

src/utils/helpers.ts
refactor: Function helper.getError
=> refactor: Function helper.getError

.env.example, .env.example.docker
chore: Add NODE_ENV config variable.
=> chore: Add NODE_ENV config variable

src/modules/Product/components/Product/ModalImage.vue, src/modules/Product/components/Product/ModalPacking.vue, src/modules/User/views/Index.vue, vite.config.ts
=> style: Z-index adjustment

src/modules/Product/components/Product/ModalImage.vue, src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/services/PresentationService.ts
feat: Create service to send the image.
=> feat: Create service to send the image

src/modules/Product/components/Product/TablePresentation.vue, src/modules/Product/services/PresentationService.ts
fix: Create service to send the image.
=> fix: Create service to send the image

src/modules/Product/composables/Product/useIndex.ts
=> feat: Remove product

src/modules/Article/components/Article/FormArticle.vue, src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TabArticle.vue, src/modules/Article/components/Article/TabArticleDetail.vue, src/modules/Article/components/Article/TableArticleDetail.vue, src/modules/Article/composables/Article/useFormArticle.ts, src/modules/Article/composables/Article/useFormArticleDetail.ts, src/modules/Article/composables/Article/useIndex.ts, src/modules/Article/composables/Article/useTabArticle.ts, src/modules/Article/composables/Article/useTabArticleDetail.ts, src/modules/Article/routes/index.ts, src/modules/Article/services/Article.ts, src/modules/Article/services/ArticleDetail.ts, src/modules/Article/types/Article/ArticleDetail.ts, src/modules/Article/types/Article/index.ts, src/modules/Article/views/Article/Index.vue, src/modules/Article/views/Article/Tabs.vue, src/modules/Product/routes/index.ts, src/router/index.ts
feat: Article module scaffold.
=> feat: Article module scaffold

src/components/AppCheckbox.vue, src/modules/Article/components/Article/FormArticle.vue, src/modules/Article/components/Article/TabArticle.vue, src/plugins/components.ts
fix: Registration is seen when editing article.
=> fix: Registration is seen when editing article

src/modules/Article/components/Article/TableArticleDetail.vue
feat: Show Categories, Mark and Packaging of Articles.
=> feat: Show Categories, Mark and Packaging of Articles

src/components/AppPaginationB.vue
=> fix: Page number buttons

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Product/components/Product/FormPresentation.vue, src/modules/Product/composables/Product/useFormPresentation.ts
refactor: Delete unnecessary fields.
=> refactor: Delete unnecessary fields

src/assets/css/app.css, src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue
feat: Design of the presentation search form for articles.
=> feat: Design of the presentation search form for articles

src/components/AppPaginationB.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Article/composables/Article/useTableGrid.ts, src/modules/Article/services/Presentation.ts
feat: Create search debounce timer to find Presentations.
=> feat: Create search debounce timer to find Presentations

src/modules/Article/components/Article/TableSearchArticleDetail.vue
feat: Show presentations in search table.
=> feat: Show presentations in search table

src/components/AppPaginationC.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue
feat: Pagination for the search presentations table.
=> feat: Pagination for the search presentations table

src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Article/composables/Article/useTableGrid.ts
feat: Search presentations to create articles.
=> feat: Search presentations to create articles

src/components/AppPaginationC.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Article/composables/Article/useTableGrid.ts
feat: Sort presentation search column.
=> feat: Sort presentation search column

src/modules/Article/components/Article/TableSearchArticleDetail.vue
feat: Control selected presentations.
=> feat: Control selected presentations

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue
refactor: Send payload from child component to parent component.
=> refactor: Send payload from child component to parent component

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.xvue
feat: Add number of presentations to the article.
=> feat: Add number of presentations to the article

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue
fix: (WIP) Input of checkout and count not working.
=> fix: (WIP) Input of checkout and count not working

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue
fix: Input of checkout and count not working.
=> fix: Input of checkout and count not working

src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/composables/Article/useTabArticleDetail.ts, src/modules/Article/services/ArticleDetail.ts
feat: Send the payload to the article service module.
=> feat: Send the payload to the article service module

src/modules/Article/composables/Article/useTabArticleDetail.ts
feat: Test the endpoint of registering article detail.
=> feat: Test the endpoint of registering article detail

src/components/AppPaginationC.vue, src/modules/Article/components/Article/FormArticleDetail.vue, src/modules/Article/components/Article/TabArticleDetail.vue, src/modules/Article/components/Article/TableArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Article/composables/Article/useTabArticleDetail.ts, src/modules/Article/composables/Article/useTableGrid.ts, src/modules/Article/services/ArticleDetail.ts, src/modules/Article/types/Article/ArticleDetail.ts
feat: Insert articles details.
=> feat: Insert articles details

src/modules/Article/components/Article/TabArticleDetail.vue, src/modules/Article/components/Article/TableArticleDetail.vue, src/modules/Article/composables/Article/useTabArticleDetail.ts, src/modules/Article/services/ArticleDetail.ts, src/modules/Article/types/Article/ArticleDetail.ts
feat: Allow deleting article details.
=> feat: Allow deleting article details

src/modules/Inventory/components/Movement/FormMovement.vue, src/modules/Inventory/components/Movement/FormMovementDetail.vue, src/modules/Inventory/components/Movement/TabMovement.vue, src/modules/Inventory/components/Movement/TabMovementDetail.vue, src/modules/Inventory/components/Movement/TableMovementDetail.vue, src/modules/Inventory/composables/Movement/useFormMovement.ts, src/modules/Inventory/composables/Movement/useFormMovementDetail.ts, src/modules/Inventory/composables/Movement/useIndex.ts, src/modules/Inventory/composables/Movement/useTabMovement.ts, src/modules/Inventory/composables/Movement/useTabMovementDetail.ts, src/modules/Inventory/routes/indexMovement.ts, src/modules/Inventory/services/Movement.ts, src/modules/Inventory/services/MovementDetail.ts, src/modules/Inventory/types/Movement/MovementDetail.ts, src/modules/Inventory/types/Movement/index.ts, src/modules/Inventory/views/Movement/Index.vue, src/modules/Inventory/views/Movement/Tabs.vue
feat: Continue with Inventory module.
=> feat: Continue with Inventory module

src/modules/Inventory/components/Movement/TabMovement.vue, src/modules/Inventory/composables/Movement/useFormMovement.ts, src/modules/Inventory/composables/Movement/useTabMovement.ts, src/modules/Inventory/routes/index.ts, src/modules/Store/routes/index.ts
feat: Shape the form of movements.
=> feat: Shape the form of movements

src/modules/Store/composables/Movement/useIndex.ts, src/modules/Store/routes/index.ts, src/modules/Store/views/Movement/Index.vue, src/modules/Store/views/Movement/Tabs.vue
feat: Implement a single view for all movements.
=> feat: Implement a single view for all movements

src/modules/Store/composables/Movement/useIndex.ts, src/modules/Store/services/Movement.ts
feat: Separate data by type of movement.
=> feat: Separate data by type of movement

src/modules/Store/components/Existence/Table.vue, src/modules/Store/composables/Existence/useExistence.ts, src/modules/Store/routes/index.ts, src/modules/Store/views/Existence.vue
feat: Mock summary existence view.
=> feat: Mock summary existence view

src/modules/Store/components/Movement/TableMovementDetail.vue
=> feat: Show movement detail

src/modules/Store/composables/Existence/useExistence.ts
=> fix: Stock existence mock

src/modules/Store/components/Existence/Table.vue, src/modules/Store/views/Existence.vue
feat: Show name and article code instead of id.
=> feat: Show name and article code instead of id

package-lock.json, package.json, src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/TabMovementDetail.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/composables/Movement/useTabMovementDetail.ts, src/modules/Store/views/Movement/Tabs.vue, src/modules/Store/views/Movement/TabsBack.vue
feat: Change and improve the UI/UX.
=> feat: Change and improve the UI/UX

src/modules/Article/services/Article.ts, src/modules/Store/components/Movement/FormMovementDetail.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/components/Movement/TableSearchDetail.vue, src/modules/Store/composables/Movement/useTableGrid.ts, src/modules/Store/views/Movement/Tabs.vue
feat: Design articles-search endpoint.
=> feat: Design articles-search endpoint

src/utils/Http/init.ts
chore: Migrating to Laravel 11
=> chore: Migrating to Laravel 11

src/layouts/Header.vue, src/modules/Auth/components/ProfileVerifyEmail.vue, src/modules/Auth/stores/getters.ts
fix: Create getter of the authenticated user_s avatar.
=> fix: Create getter of the authenticated user_s avatar

src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/FormMovementDetail.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/composables/Movement/useFormMovement.ts, src/modules/Store/views/Movement/Tabs.vue
feat: Improve the design of the movements form.
=> feat: Improve the design of the movements form

src/modules/Store/components/Movement/TableSearchDetail.vue
feat: Search articles to movement.
=> feat: Search articles to movement

src/modules/Store/components/Movement/FormMovementDetail.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/components/Movement/TableSearchDetail.vue, src/modules/Store/components/Movement/xTabMovementDetail.vue, src/modules/Store/composables/Movement/useTabMovementDetail.ts, src/modules/Store/views/Movement/CreateOrEdit.vue
feat: Add articles to the temporary movement details table.
=> feat: Add articles to the temporary movement details table

src/modules/Store/components/Movement/FormMovementDetail.vue, src/modules/Store/composables/Movement/useTabMovement.ts, src/modules/Store/composables/Movement/useTabMovementDetail.ts, src/modules/Store/views/Movement/CreateOrEdit.vue
feat: Build the movement payload.
=> feat: Build the movement payload

src/modules/Store/components/Movement copy/FormMovement.vue, src/modules/Store/components/Movement copy/FormMovementDetail.vue, src/modules/Store/components/Movement copy/TabMovement.vue, src/modules/Store/components/Movement copy/TableMovementDetail.vue, src/modules/Store/components/Movement copy/TableSearchDetail.vue, src/modules/Store/components/Movement copy/xTabMovementDetail.vue, src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/composables/Movement copy/useFormMovement.ts, src/modules/Store/composables/Movement copy/useFormMovementDetail.ts, src/modules/Store/composables/Movement copy/useIndex.ts, src/modules/Store/composables/Movement copy/useTabMovement.ts, src/modules/Store/composables/Movement copy/useTabMovementDetail.ts, src/modules/Store/composables/Movement copy/useTableGrid.ts, src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/views/Movement copy/CreateOrEdit.vue, src/modules/Store/views/Movement copy/Index.vue, src/modules/Store/views/Movement/CreateOrEdit.vue
refactor: (WIP) Reconstruction of the CreateOrEdit page.
=> refactor: (WIP) Reconstruction of the CreateOrEdit page

src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/FormMovementDetail.vue, src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/components/Movement/TableSearchDetail.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/composables/Movement/useTabMovementDetail.ts, src/modules/Store/views/Movement/CreateOrEdit.vue
refactor: Reconstruction of the CreateOrEdit page.
=> refactor: Reconstruction of the CreateOrEdit page

src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/FormMovementMain.vue
Develop: feat: Lock fields when show.
=> Develop: feat: Lock fields when show

src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/views/Movement/Index.vue
feat: Redirect page after insert.
=> feat: Redirect page after insert

src/modules/Article/types/Article/ArticleDetail.ts, src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/composables/Movement/useMovement.ts
=> feat: Validate movement form

src/modules/Store/components/DailyClosing/FormDailyClosing.vue, src/modules/Store/components/DailyClosing/PreDailyClosing.vue, src/modules/Store/composables/DailyClosing/useDailyClosing.ts, src/modules/Store/composables/DailyClosing/useFormDailyClosing.ts, src/modules/Store/routes/index.ts, src/modules/Store/views/DailyClosing/Create.vue
feat: Design of the form for the daily pre-closing.
=> feat: Design of the form for the daily pre-closing

src/modules/Store/composables/DailyClosing/useDailyClosing.ts, src/modules/Store/routes/index.ts, src/modules/Store/services/DaylyClosing.ts, src/modules/Store/views/DailyClosing/Index.vue, src/modules/Store/views/DailyClosing/Show.vue
=> feat: Show daily closing

src/modules/Store/composables/DailyClosing/useDailyClosing.ts, src/modules/Store/views/DailyClosing/Show.vue
=> fix: Show daily closing

src/modules/Store/components/Existence/Table.vue
feat: Add id to article description.
=> feat: Add id to article description

src/modules/Product/types/Presentation.ts, src/modules/Store/components/Existence/Table.vue, src/modules/Store/composables/DailyClosing/useIndex.ts, src/modules/Store/composables/Movement/useIndex.ts, src/modules/Store/services/MovementDetail.ts
feat: Consume stocks by accumulated plus unclosed movements.
=> feat: Consume stocks by accumulated plus unclosed movements

src/modules/Store/components/Movement/TableMovementDetail.vue
feat: Show article id in table movement detail.
=> feat: Show article id in table movement detail

src/modules/Store/components/Existence/Table.vue, src/modules/Store/composables/DailyClosing/useDailyClosing.ts, src/modules/Store/views/DailyClosing/Show.vue
feat: Add cumulative field to daily closing table.
=> feat: Add cumulative field to daily closing table

src/layouts/Header.vue, src/modules/Store/stores/actions.ts, src/modules/Store/stores/getters.ts, src/modules/Store/stores/index.ts, src/modules/Store/stores/state.ts, src/modules/Store/types/Store/SubStore.ts
feat: Global sub warehouse status.
=> feat: Global sub warehouse status

src/modules/Store/components/Existence/Table.vue
feat: Reorder the position of the stock columns.
=> feat: Reorder the position of the stock columns

src/modules/Store/components/SubWarehouse/FormCreateOrEdit.vue, src/modules/Store/composables/SubWarehouse/useCreateOrEdit.ts, src/modules/Store/composables/SubWarehouse/useIndex.ts, src/modules/Store/routes/index.ts, src/modules/Store/services/SubWarehouse.ts, src/modules/Store/types/SubWarehouse/index.ts, src/modules/Store/views/SubWarehouse/CreateOrEdit.vue, src/modules/Store/views/SubWarehouse/Index.vue
=> feat: SubWarehouse crud

src/layouts/Header.vue, src/modules/Store/components/SubWarehouse/SelectSubWarehouse.vue
feat: Create the SelectSubWarehouse component.
=> feat: Create the SelectSubWarehouse component

src/modules/Store/components/SubWarehouse/SelectSubWarehouse.vue
feat: Consume get-help-sub-warehouses api point.
=> feat: Consume get-help-sub-warehouses api point

src/modules/Store/components/SubWarehouse/SelectSubWarehouse.vue, src/modules/Store/composables/SubWarehouse/useCreateOrEdit.ts
feat: Insert sub warehouses with uuid and not overwrite it with the update.
=> feat: Insert sub warehouses with uuid and not overwrite it with the update

src/modules/Store/views/SubWarehouse/CreateOrEdit.vue, src/modules/Store/views/SubWarehouse/Index.vue
chore: Change title to Spanish.
=> chore: Change title to Spanish

src/layouts/Header.vue, src/modules/Store/components/SubWarehouse/SelectSubWarehouse.vue
style: Center select-sub-warehouse element as title.
=> style: Center select-sub-warehouse element as title

src/modules/Article/composables/Article/useTabArticleDetail.ts
fix: The article form does not allow loading combos.
=> fix: The article form does not allow loading combos

src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/types/Movement.ts
feat: Save store_uuid at movements table.
=> feat: Save store_uuid at movements table

Dockerfile, vite.config.ts
=> feat: Update containers

src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, vite.config.ts
feat: Create button to search for support information.
=> feat: Create button to search for support information

src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/services/MovementDetail.ts
feat: Consume endpoint to get movement details by number.
=> feat: Consume endpoint to get movement details by number

src/modules/Store/components/Movement/FormMovement.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/views/Movement/CreateOrEdit.vue
feat: Show details of the movement obtained by number.
=> feat: Show details of the movement obtained by number

src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/components/Movement/TableMovementDetail.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/views/Movement/Index.vue
feat: Validate type of movement before returning its details.
=> feat: Validate type of movement before returning its details

src/modules/Store/composables/Movement/useMovement.ts, src/modules/Store/types/Movement.ts, src/modules/Store/views/Movement/Index.vue
fix: It is not reversing correctly.
=> fix: It is not reversing correctly

index.html, src/components/AppPaginationB.vue, src/modules/Article/components/Article/FormArticle.vue, src/modules/Article/components/Article/TabArticleDetail.vue, src/modules/Article/components/Article/TableSearchArticleDetail.vue, src/modules/Article/composables/Article/useFormArticle.ts, src/modules/Article/views/Article/Index.vue, src/modules/Article/views/Article/Tabs.vue, src/modules/Authorization/views/Menus/Create.vue, src/modules/Authorization/views/Menus/Edit.vue, src/modules/Product/composables/Product/useFormPacking.ts, src/modules/Product/composables/Product/useFormPresentation.ts, src/modules/Product/composables/Product/useTabPresentation.ts, src/modules/Product/types/Presentation.ts, src/modules/Product/views/Category/Create.vue, src/modules/Product/views/Category/Edit.vue, src/modules/Product/views/Product/Index.vue, src/modules/Store/components/Movement/FormMovementMain.vue, src/modules/Store/components/Movement/TableSearchDetail.vue, src/modules/Store/composables/Movement/useFormMovementMain.ts, src/modules/Store/composables/Movement/useMovementDetail.ts, src/modules/Store/composables/Movement/useMovementType.ts, src/modules/Store/types/Movement.ts, src/modules/Store/views/DailyClosing/Index.vue, src/modules/Store/views/Movement/Index.vue
=> fix: Various new things

src/modules/Article/components/Article/TabArticleDetail.vue, src/modules/Product/views/Product/Tabs.vue
feat: Detail form is disabled until the main has been registered.
=> feat: Detail form is disabled until the main has been registered

src/modules/Store/composables/Existence/useExistence.ts, src/modules/Store/composables/Existence/useExistenceBackup.ts, src/modules/Store/services/Existences.ts, src/modules/Store/views/Existence.vue, src/modules/Store/views/ExistenceBackup.vue
feat: Add pagination, search and sort to the stock datagrid.
=> feat: Add pagination, search and sort to the stock datagrid

package-lock.json, package.json, src/modules/Auth/views/Dashboard.vue, src/plugins/apexcharts.ts, src/plugins/index.ts
feat: Incorporating graphics into the dashboard.
=> feat: Incorporating graphics into the dashboard
